services:
  postgres_db:
    container_name: base-datos_a-la-carta
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    restart: always

  pgadmin:
    container_name: pgadmin_web
    image: dpage/pgadmin4:7
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    ports:
      - "5050:80"
    restart: always
    depends_on:
      - postgres_db

  web_app_env_dev:
    container_name: web_app_dev
    build: .
    ports:
      - "3000:3000"
    command: yarn dev
    volumes:
      - .:/web_app
    depends_on:
      - postgres_db
